version: '2'
services:

  backend1:
    image: my-host/docker_network-backend
    networks:
      docker_network_demo:
        aliases:
          - backend1
    
networks:
  docker_network_demo:
    external:
      name: demonetwork_demo