version: '2'
services:

  backend1:
    image: my-host/docker_network-backend
    networks:
      docker_network_private1:
        aliases:
          - backend1
    
networks:
  docker_network_private1:
    external:
      name: demonetwork_private1